import React, { useState } from "react";
import { Link } from "react-router-dom";
import { listPlatformHotels } from "../../services/firebasePlatform";
import { usePlatformQuery } from "../../hooks/usePlatformQuery";
import { Title, QueryState, Status, button, primary, panel, Moment } from "./PlatformShared";

export default function PlatformHotelsPage({ overview = false }) {
  const [cursor, setCursor] = useState(null), [previous, setPrevious] = useState([]), [search, setSearch] = useState("");
  const query = usePlatformQuery(() => listPlatformHotels(cursor), cursor);
  const hotels = query.data?.hotels || [];
  const active = (sub) => ["active", "trialing"].includes(sub?.status) && (sub.validUntilMillis == null ? sub.status === "active" : sub.validUntilMillis > Date.now());
  return <><Title title={overview ? "Platform overview" : "Hotels"} actions={<Link className={primary} to="/platform/hotels/new">Set up a hotel</Link>}>Manage properties and licensed modules. Monitoring summaries show when they were last checked.</Title>
    <QueryState query={query}>{overview && <div className="mb-6 grid gap-4 sm:grid-cols-3">{[["Hotels on this page", hotels.length], ["Active access on this page", hotels.filter((row) => active(row.subscription)).length], ["Monitoring needs attention", hotels.filter((row) => row.health?.status === "attention").length]].map(([label, value]) => <div key={label} className={panel}><p className="text-sm text-slate-500">{label}</p><p className="mt-3 text-3xl font-semibold">{value}</p></div>)}</div>}
      <div className={panel}><div className="mb-5 flex flex-wrap items-center justify-between gap-3"><label className="text-sm">Find on this page<input aria-label="Find hotel on this page" value={search} onChange={(event) => setSearch(event.target.value)} className="ml-3 rounded-lg border p-2" /></label><button className={button} onClick={query.refresh}>Refresh</button></div>
        {!hotels.length ? <p>No hotels have been created. Set up your first hotel and appoint its administrators.</p> : <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b text-slate-500"><th className="p-3">Hotel</th><th className="p-3">Subscription</th><th className="p-3">Modules</th><th className="p-3">Imports</th><th className="p-3">Last check</th></tr></thead><tbody>{hotels.filter((row) => `${row.name} ${row.hotelUid}`.toLowerCase().includes(search.toLowerCase())).map((row) => <tr key={row.hotelUid} className="border-b last:border-0"><td className="p-3"><Link className="font-semibold text-slate-900 underline decoration-slate-300 underline-offset-4" to={`/platform/hotels/${row.hotelUid}`}>{row.name}</Link><p className="mt-1 text-xs text-slate-500">{row.hotelUid}</p></td><td className="p-3"><Status value={row.subscription ? active(row.subscription) ? row.subscription.status : ["active", "trialing"].includes(row.subscription.status) ? "expired" : row.subscription.status : "unconfigured"} /></td><td className="p-3">{row.subscription?.modules ? row.subscription.modules.length ? row.subscription.modules.join(", ") : "Core only" : "Assignment required"}</td><td className="p-3"><Status value={row.health?.status || "unknown"} /></td><td className="p-3"><Moment value={row.health?.computedAtMillis} /></td></tr>)}</tbody></table></div>}
        <div className="mt-5 flex justify-between"><button disabled={!previous.length} className={button} onClick={() => { setCursor(previous.at(-1)); setPrevious(previous.slice(0, -1)); }}>Previous page</button><button disabled={!query.data?.nextCursor} className={button} onClick={() => { setPrevious([...previous, cursor]); setCursor(query.data.nextCursor); }}>Next page</button></div>
      </div>
      {overview && <div className={`${panel} mt-6`}><h2 className="font-semibold">Daily operations</h2><p className="mt-2 text-sm text-slate-600">Configure expected imports per hotel. Unconfigured or stale monitoring is shown as unknown; it does not prove a healthy integration.</p><div className="mt-4 flex flex-wrap gap-3"><Link className={button} to="/platform/imports">Inspect imports</Link><Link className={button} to="/platform/incidents">Review notifications</Link></div></div>}
    </QueryState></>;
}
