import React, { useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import HeaderBar from "../layout/HeaderBar";
import PageContainer from "../layout/PageContainer";
import { Card } from "../layout/Card";
import { auth, signOut } from "../../firebaseConfig";
import { useHotelContext } from "../../contexts/HotelContext";
import { getCompetitorGroupObservations, subscribeQuotes } from "../../services/firebaseQuotes";
import { averageQuoteVariance, decisionWinRate, frozenDecisionValue, leadTimeBand } from "../../utils/commercialIntelligence";
import { formatHotelStayDate } from "../../utils/hotelStayDates";

const money = (v) => v == null ? "Unavailable" : `€${Number(v).toFixed(2)}`;
const pct = (v) => v == null ? "Unavailable" : `${(v * 100).toFixed(1)}%`;
const timestampDate = (v) => v?.toDate?.()?.toISOString?.().slice(0, 10) || String(v || "").slice(0, 10);
const rn = (q) => (q.roomsByDate || []).reduce((s, n) => s + Math.max(0, Number(n.rooms) || 0), 0);
const winRate = (rows) => pct(decisionWinRate(rows));

export default function CommercialIntelligencePage() {
  const { hotelUid } = useHotelContext(); const [tab, setTab] = useState("performance"); const [quotes, setQuotes] = useState([]); const [observations, setObservations] = useState([]);
  const [from, setFrom] = useState(() => { const d = new Date(); d.setUTCFullYear(d.getUTCFullYear() - 1); return d.toISOString().slice(0, 10); });
  const [to, setTo] = useState(() => new Date().toISOString().slice(0, 10)); const [status, setStatus] = useState("ALL");
  useEffect(() => hotelUid ? subscribeQuotes(hotelUid, setQuotes) : undefined, [hotelUid]);
  useEffect(() => { if (hotelUid) getCompetitorGroupObservations(hotelUid).then(setObservations); }, [hotelUid]);
  const filtered = useMemo(() => quotes.filter((q) => { const date = timestampDate(q.outcome?.decidedAt) || timestampDate(q.createdAt) || q.requestDate; return (!date || (date >= from && date <= to)) && (status === "ALL" || q.commercialStatus === status); }), [quotes, from, to, status]);
  const counts = Object.fromEntries(["PENDING","WON","LOST","DECLINED","CANCELLED"].map((s) => [s, filtered.filter((q) => q.commercialStatus === s).length]));
  const variance = ["targetRateInclVat","economicFloorRateInclVat","stretchRateInclVat"].map((field) => [field, averageQuoteVariance(filtered, field)]);
  const group = (keyFn) => Object.values(filtered.reduce((all, q) => { const key = keyFn(q); (all[key] ||= { key, rows: [] }).rows.push(q); return all; }, {}));
  const breakdown = (title, rows) => <Card><h2 className="text-lg font-semibold">{title}</h2><div className="mt-3 overflow-x-auto"><table className="w-full text-sm"><thead><tr className="text-left text-gray-500"><th>Band</th><th>Quotes</th><th>Won</th><th>Lost</th><th>Win rate</th></tr></thead><tbody>{rows.map(({key,rows})=><tr className="border-t" key={key}><td className="py-2 font-medium">{key}</td><td>{rows.length}</td><td>{rows.filter(q=>q.commercialStatus==="WON").length}</td><td>{rows.filter(q=>q.commercialStatus==="LOST").length}</td><td>{winRate(rows)} (N={rows.filter(q=>["WON","LOST"].includes(q.commercialStatus)).length})</td></tr>)}</tbody></table></div></Card>;
  const reasonTable = (title, decision, field) => { const rows = Object.entries(filtered.filter(q=>q.commercialStatus===decision).reduce((a,q)=>{ const k=q.outcome?.[field]||"UNKNOWN"; a[k]=(a[k]||0)+1; return a;},{})).sort((a,b)=>b[1]-a[1]); const total=rows.reduce((s,r)=>s+r[1],0); return <Card><h2 className="text-lg font-semibold">{title}</h2>{rows.length?<ul className="mt-3 space-y-2">{rows.map(([k,n])=><li key={k} className="flex justify-between border-b pb-1"><span>{k}</span><strong>{n} · {pct(n/total)}</strong></li>)}</ul>:<p className="mt-3 text-sm text-gray-500">No records in the selected period.</p>}</Card> };
  const logout=async()=>{await signOut(auth); window.location.href="/login";};
  return <div className="min-h-screen bg-gray-50"><HeaderBar today={new Date().toLocaleDateString()} onLogout={logout}/><PageContainer className="space-y-5 pb-10"><div><p className="text-sm uppercase text-gray-500">Revenue</p><h1 className="text-3xl font-semibold">Commercial Intelligence</h1><p className="text-gray-600">Factual performance and observed competitor intelligence; no pricing recommendation or prediction.</p></div><div className="flex gap-2 border-b">{[["performance","Performance"],["competitors","Competitor Intelligence"]].map(([id,label])=><button className={`px-4 py-3 font-semibold ${tab===id?"border-b-2 border-[#b41f1f] text-[#b41f1f]":""}`} onClick={()=>setTab(id)} key={id}>{label}</button>)}</div>
  {tab==="performance"?<><Card className="flex flex-wrap gap-4"><label className="text-sm">Decided/requested from<input className="ml-2 rounded border p-2" type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label className="text-sm">To<input className="ml-2 rounded border p-2" type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><label className="text-sm">Status<select className="ml-2 rounded border p-2" value={status} onChange={e=>setStatus(e.target.value)}><option>ALL</option>{Object.keys(counts).map(s=><option key={s}>{s}</option>)}</select></label></Card><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[["Total Quotes",filtered.length],...Object.entries(counts),["Decision Win Rate",`${winRate(filtered)} (N=${counts.WON+counts.LOST})`],["Requested RN",filtered.reduce((s,q)=>s+rn(q),0)],["Won RN",filtered.filter(q=>q.commercialStatus==="WON").reduce((s,q)=>s+rn(q),0)]].map(([k,v])=><Card key={k}><p className="text-xs uppercase text-gray-500">{k}</p><p className="text-2xl font-semibold">{v}</p>{k==="Decision Win Rate"&&<p className="text-xs text-gray-500">WON / (WON + LOST)</p>}</Card>)}</div><div className="grid gap-3 lg:grid-cols-3">{variance.map(([field,v])=><Card key={field}><p className="text-xs uppercase text-gray-500">Average Final vs {field.replace("RateInclVat","")}</p><p className="text-xl font-semibold">{money(v.amount)} · {pct(v.percentage)}</p><p className="text-xs text-gray-500">Only complete frozen snapshots · N={v.sampleCount}</p></Card>)}</div>{filtered.length===0&&<Card>No decided quotes in the selected period.</Card>}<div className="grid gap-4 lg:grid-cols-2">{breakdown("Performance by displacement band",group(q=>frozenDecisionValue(q,"yieldBand")||"UNAVAILABLE"))}{breakdown("Performance by lead time",group(q=>leadTimeBand(q.leadTimeDays ?? (q.requestDate&&q.startDate ? Math.round((Date.parse(q.startDate)-Date.parse(q.requestDate))/86400000):null))))}{breakdown("Performance by market demand",group(q=>{const d=frozenDecisionValue(q,"weightedMarketDemand"); return d==null?"Market data unavailable":d<.5?"<50%":d<.7?"50–69%":d<.85?"70–84%":"85%+";}))}{breakdown("Performance by segment",group(q=>q.groupSegment||"UNKNOWN"))}{reasonTable("Lost reasons","LOST","lostReason")}{reasonTable("Declined reasons","DECLINED","declinedReason")}</div></>:
  <><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[["Total Observations",observations.length],["Competitors Observed",new Set(observations.map(o=>o.competitorId)).size],["Lost-Group Observations",observations.filter(o=>o.sourceType==="LOST_GROUP").length],["Manual / Sales Intelligence",observations.filter(o=>["MANUAL_OBSERVATION","SALES_INTELLIGENCE"].includes(o.sourceType)).length]].map(([k,v])=><Card key={k}><p className="text-xs uppercase text-gray-500">{k}</p><p className="text-2xl font-semibold">{v}</p></Card>)}</div><Card className="border-amber-300 bg-amber-50"><strong>Raw observed group rates — not product normalized.</strong><p className="text-sm">Rates may differ in meal basis, occupancy, room type, cancellation terms, date pattern, group size and inclusions. No public/group normalization exists.</p></Card>{!observations.length?<Card>Competitor intelligence will populate as LOST quotes and manual observations are recorded.</Card>:<Card className="overflow-x-auto"><table className="min-w-[1000px] w-full text-sm"><thead><tr className="text-left text-gray-500">{["Observed At","Competitor","Stay Dates","Requested RN","Observed Group Rate","Meal Basis","Lead Time","Segment","Source","Confidence","Source Quote"].map(h=><th className="p-2" key={h}>{h}</th>)}</tr></thead><tbody>{observations.map(o=><tr className="border-t" key={o.id}><td className="p-2">{timestampDate(o.observedAt)||"—"}</td><td>{o.competitorName||o.competitorId}</td><td>{formatHotelStayDate(o.stayStartDate)} – {formatHotelStayDate(o.checkOutDate||o.stayEndDate)}</td><td>{o.requestedRoomNights??"—"}</td><td>{money(o.competitorQuotedRateInclVat)}</td><td>{o.mealBasis}</td><td>{o.leadTimeDays==null?"—":`${o.leadTimeDays} days`}</td><td>{o.groupSegment||"UNKNOWN"}</td><td>{o.sourceType}</td><td>{o.sourceConfidence}</td><td>{o.sourceQuoteId?<Link className="text-[#b41f1f] underline" to={`/revenue/group-quotes/${o.sourceQuoteId}`}>Open source quote</Link>:"—"}{o.publicRatesByDate?.length>0&&<details><summary className="cursor-pointer">Saved public rates</summary>{o.publicRatesByDate.map(r=><div key={r.stayDate}>{formatHotelStayDate(r.stayDate)} {money(r.publicRateInclVat)}</div>)}</details>}</td></tr>)}</tbody></table></Card>}</>}</PageContainer></div>;
}
