import React, { useEffect, useMemo, useState } from "react";
import { getCompsetConfiguration, getCompetitorGroupObservationCounts, saveCompsetConfiguration } from "../../services/firebaseQuotes";
import { DEFAULT_PRICING_STRATEGY, normalizePricingStrategy } from "../../utils/pricingGuidance";

const blankCompetitor = (index) => ({ id: `competitor-${index + 1}`, displayName: "", lighthouseFieldName: "", active: true, includeInMarketContext: true, marketRelevanceWeight: 0, groupIntelligenceEnabled: true, strategyNotes: "", sortOrder: index });

export default function CompsetSettings({ hotelUid }) {
  const [settings, setSettings] = useState({ ownHotelLighthouseFieldName: "", pricingStrategy: DEFAULT_PRICING_STRATEGY });
  const [competitors, setCompetitors] = useState([]);
  const [observationCounts, setObservationCounts] = useState({});
  const [saving, setSaving] = useState(false);
  const [message, setMessage] = useState("");
  useEffect(() => { if (hotelUid) Promise.all([getCompsetConfiguration(hotelUid), getCompetitorGroupObservationCounts(hotelUid)]).then(([data, counts]) => { setSettings({ ...data.settings, pricingStrategy: normalizePricingStrategy(data.settings.pricingStrategy) }); setCompetitors(data.competitors); setObservationCounts(counts); }); }, [hotelUid]);
  const includedWeight = useMemo(() => competitors.filter((item) => item.active && item.includeInMarketContext && Number(item.marketRelevanceWeight) > 0).reduce((sum, item) => sum + Number(item.marketRelevanceWeight), 0), [competitors]);
  const update = (index, key, value) => setCompetitors((current) => current.map((item, position) => position === index ? { ...item, [key]: value } : item));
  const strategy = settings.pricingStrategy || DEFAULT_PRICING_STRATEGY;
  const updateStrategyPercent = (key, value) => setSettings({ ...settings, pricingStrategy: { ...strategy, [key]: Number(value) / 100 } });
  const percentageField = (label, key) => <label className="text-sm">{label}<input required min="0" max="100" step="0.1" type="number" value={Number(strategy[key]) * 100} onChange={(event) => updateStrategyPercent(key, event.target.value)} className="mt-1 w-full rounded border px-2 py-1" /></label>;
  const submit = async (event) => { event.preventDefault(); setSaving(true); setMessage(""); try { await saveCompsetConfiguration(hotelUid, settings, competitors); setMessage("Market pricing configuration saved."); } catch (error) { setMessage(error.message); } finally { setSaving(false); } };
  return <form onSubmit={submit} className="space-y-5">
    <div><p className="text-xs font-semibold uppercase tracking-widest text-gray-500">Market Pricing</p><h2 className="text-xl font-semibold">Compset configuration</h2><p className="text-sm text-gray-600">Lighthouse public consumer rates already include VAT. Weights are normalized automatically and do not need to total 100.</p></div>
    <div className="grid gap-3 sm:grid-cols-2"><label className="block text-sm font-semibold">Own Lighthouse field mapping<input value={settings.ownHotelLighthouseFieldName || ""} onChange={(e) => setSettings({ ...settings, ownHotelLighthouseFieldName: e.target.value })} className="mt-1 w-full rounded border px-3 py-2 font-normal" placeholder="Exact Lighthouse column name" /></label><label className="block text-sm font-semibold">Global Maximum Usable Public Rate (€; optional)<input min="0" step=".01" type="number" value={settings.maxUsablePublicRateInclVat ?? ""} onChange={(e) => setSettings({ ...settings, maxUsablePublicRateInclVat: e.target.value === "" ? null : Number(e.target.value) })} className="mt-1 w-full rounded border px-3 py-2 font-normal" /></label></div>
    <div className="space-y-4">{competitors.map((item, index) => <fieldset key={item.id} className="rounded-lg border border-gray-200 p-4"><legend className="px-1 font-semibold">{item.displayName || item.id} <span className="ml-2 text-xs font-normal text-gray-500">{observationCounts[item.id] || 0} observations</span></legend><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
      <label className="text-sm">ID<input required value={item.id} onChange={(e) => update(index, "id", e.target.value)} className="mt-1 w-full rounded border px-2 py-1" /></label><label className="text-sm">Display name<input required value={item.displayName || ""} onChange={(e) => update(index, "displayName", e.target.value)} className="mt-1 w-full rounded border px-2 py-1" /></label><label className="text-sm">Lighthouse field<input value={item.lighthouseFieldName || ""} onChange={(e) => update(index, "lighthouseFieldName", e.target.value)} className="mt-1 w-full rounded border px-2 py-1" /></label>
      <label className="text-sm">Relevance weight<input min="0" required type="number" step="0.01" value={item.marketRelevanceWeight} onChange={(e) => update(index, "marketRelevanceWeight", e.target.value)} className="mt-1 w-full rounded border px-2 py-1" /><span className="text-xs text-gray-500">Effective: {includedWeight && item.active && item.includeInMarketContext ? `${(Number(item.marketRelevanceWeight) / includedWeight * 100).toFixed(1)}%` : "0.0%"}</span></label>
      <label className="text-sm">Maximum Usable Public Rate (€)<input min="0" step=".01" type="number" value={item.maxUsablePublicRateInclVat ?? ""} onChange={(e) => update(index, "maxUsablePublicRateInclVat", e.target.value === "" ? null : Number(e.target.value))} className="mt-1 w-full rounded border px-2 py-1" /></label><label className="text-sm">Known Placeholder Rates<input value={(item.placeholderPublicRatesInclVat || []).join(", ")} onChange={(e) => update(index, "placeholderPublicRatesInclVat", e.target.value.split(",").map((value) => value.trim()).filter(Boolean).map(Number).filter(Number.isFinite))} placeholder="800, 999" className="mt-1 w-full rounded border px-2 py-1" /></label><label className="text-sm">Reliable Booking Horizon (days)<input min="0" step="1" type="number" value={item.maxReliableLeadTimeDays ?? ""} onChange={(e) => update(index, "maxReliableLeadTimeDays", e.target.value === "" ? null : Number(e.target.value))} className="mt-1 w-full rounded border px-2 py-1" /></label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={Boolean(item.active)} onChange={(e) => update(index, "active", e.target.checked)} /> Active</label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={Boolean(item.includeInMarketContext)} onChange={(e) => update(index, "includeInMarketContext", e.target.checked)} /> Include in market context</label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={Boolean(item.groupIntelligenceEnabled)} onChange={(e) => update(index, "groupIntelligenceEnabled", e.target.checked)} /> Group intelligence enabled</label>
      <label className="text-sm lg:col-span-4">Strategy notes (informational only)<textarea value={item.strategyNotes || ""} onChange={(e) => update(index, "strategyNotes", e.target.value)} className="mt-1 w-full rounded border px-2 py-1" /></label>
    <p className="text-xs text-gray-500 lg:col-span-4">Rates above the configured maximum or matching known placeholder values are shown for context but excluded from market pricing calculations.</p></div></fieldset>)}</div>
    <section className="space-y-4 rounded-lg border border-indigo-200 bg-indigo-50/40 p-4"><div><h3 className="font-semibold">Pricing Guidance V1</h3><p className="text-sm text-gray-600">Editable capture assumptions for the rule-based commercial corridor. Uplifts are percentage points.</p></div><fieldset><legend className="mb-2 text-sm font-semibold">Displacement yield bands</legend><div className="grid gap-3 sm:grid-cols-2">{percentageField("Low displacement upper bound %", "lowDisplacementUpperBound")}{percentageField("High displacement lower bound %", "highDisplacementLowerBound")}</div></fieldset><fieldset><legend className="mb-2 text-sm font-semibold">Market capture by yield band</legend><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{percentageField("Low · Target %", "targetMarketCaptureLow")}{percentageField("Low · Stretch %", "stretchMarketCaptureLow")}{percentageField("Medium · Target %", "targetMarketCaptureMedium")}{percentageField("Medium · Stretch %", "stretchMarketCaptureMedium")}{percentageField("High · Target %", "targetMarketCaptureHigh")}{percentageField("High · Stretch %", "stretchMarketCaptureHigh")}</div></fieldset><fieldset><legend className="mb-2 text-sm font-semibold">Demand pressure</legend><div className="grid gap-3 sm:grid-cols-2">{percentageField("High Market Demand threshold %", "highMarketDemandThreshold")}{percentageField("Capture uplift · percentage points", "highMarketDemandCaptureUplift")}</div></fieldset><fieldset><legend className="mb-2 text-sm font-semibold">Availability pressure</legend><div className="grid gap-3 sm:grid-cols-2">{percentageField("Sold-out relevance-weight threshold %", "soldOutWeightThreshold")}{percentageField("Capture uplift · percentage points", "soldOutCaptureUplift")}</div></fieldset><label className="block max-w-xs text-sm">Commercial rounding step (€)<input required min="0.01" step="0.01" type="number" value={strategy.recommendedRateRoundingStep} onChange={(event) => setSettings({ ...settings, pricingStrategy: { ...strategy, recommendedRateRoundingStep: Number(event.target.value) } })} className="mt-1 w-full rounded border px-2 py-1" /></label></section>
    <div className="flex gap-3"><button type="button" onClick={() => setCompetitors([...competitors, blankCompetitor(competitors.length)])} className="rounded border px-4 py-2 text-sm font-semibold">Add competitor</button><button disabled={saving} className="rounded bg-[#b41f1f] px-4 py-2 text-sm font-semibold text-white disabled:bg-gray-400">{saving ? "Saving…" : "Save Compset"}</button></div>{message && <p role="status" className="text-sm font-medium">{message}</p>}
  </form>;
}
