import React, { useEffect, useState } from "react";
import { ArrowLeft, Pencil, Plus, Save, Trash2, X } from "lucide-react";
import { useNavigate } from "react-router-dom";
import { toast } from "react-toastify";
import ConfirmModal from "../layout/ConfirmModal";
import DataListTable from "../shared/DataListTable";
import { useHotelContext } from "../../contexts/HotelContext";
import { DEMAND_EFFECTS, EMPTY_CATEGORY, IMPACT_LEVELS, SYSTEM_TYPES } from "../../constants/demandCalendar";
import { createDemandCalendarCategory, deleteDemandCalendarCategory, subscribeDemandCalendarCategories, updateDemandCalendarCategory } from "../../services/firebaseDemandCalendar";
import DemandCalendarShell from "./DemandCalendarShell";

const control = "mt-1 w-full rounded-lg border border-gray-300 px-3 py-2 text-sm";
const defaults = [["defaultImpactLevel", "Default Impact Level", IMPACT_LEVELS], ["defaultGroupDemandEffect", "Default Group Demand Effect", DEMAND_EFFECTS], ["defaultTransientBusinessEffect", "Default Business Transient Effect", DEMAND_EFFECTS], ["defaultTransientLeisureEffect", "Default Leisure Transient Effect", DEMAND_EFFECTS], ["defaultBqtDemandEffect", "Default Banqueting Demand Effect", DEMAND_EFFECTS]];
export default function DemandCalendarCategoriesPage() {
  const { hotelUid } = useHotelContext(); const navigate = useNavigate(); const [categories, setCategories] = useState([]); const [form, setForm] = useState(null); const [saving, setSaving] = useState(false); const [deleteItem, setDeleteItem] = useState(null);
  useEffect(() => subscribeDemandCalendarCategories(hotelUid, setCategories, () => toast.error("Categories could not be loaded.")), [hotelUid]);
  const change = (e) => setForm((current) => ({ ...current, [e.target.name]: e.target.type === "checkbox" ? e.target.checked : e.target.value }));
  const save = async (e) => { e.preventDefault(); if (!form.name.trim() || !form.systemType) return toast.error("Category Name and System Type are required."); setSaving(true); try { const payload = { ...form }; delete payload.id; form.id ? await updateDemandCalendarCategory(hotelUid, form.id, payload) : await createDemandCalendarCategory(hotelUid, payload); setForm(null); toast.success("Category saved."); } catch { toast.error("Category could not be saved."); } finally { setSaving(false); } };
  const columns = [{ key: "name", label: "Category Name", render: (c) => <span className="font-semibold">{c.name}</span> }, { key: "systemType", label: "System Type", render: (c) => SYSTEM_TYPES[c.systemType] }, { key: "defaultImpactLevel", label: "Default Impact", render: (c) => IMPACT_LEVELS[c.defaultImpactLevel] }, { key: "active", label: "Active", render: (c) => c.active ? "Active" : "Inactive" }, { key: "actions", label: "Actions", sortable: false, render: (c) => <div className="flex gap-1"><button onClick={() => setForm({ ...EMPTY_CATEGORY, ...c })} title="Edit Category" className="rounded border p-1.5"><Pencil className="h-4 w-4" /></button><button onClick={() => setDeleteItem(c)} title="Delete Category" className="rounded border border-red-200 p-1.5 text-red-700"><Trash2 className="h-4 w-4" /></button></div> }];
  return <DemandCalendarShell><div className="flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-3"><button onClick={() => navigate("/me/demand-calendar")} className="rounded-lg border bg-white p-2"><ArrowLeft className="h-5 w-5" /></button><div><p className="text-sm uppercase tracking-wide text-gray-500">M&amp;E / Demand Calendar</p><h1 className="text-3xl font-semibold">Demand Calendar Categories</h1><p className="text-gray-600">Configure reusable categories and their event defaults.</p></div></div><button onClick={() => setForm({ ...EMPTY_CATEGORY })} className="inline-flex items-center gap-2 rounded-lg bg-[#b41f1f] px-4 py-2 font-semibold text-white"><Plus className="h-4 w-4" />Create Category</button></div>
    {form && <form onSubmit={save} className="rounded-xl border bg-white p-5 shadow-sm"><div className="mb-4 flex justify-between"><h2 className="text-lg font-semibold">{form.id ? "Edit Category" : "Create Category"}</h2><button type="button" onClick={() => setForm(null)}><X className="h-5 w-5" /></button></div><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium">Category Name *<input className={control} name="name" value={form.name} onChange={change} required /></label><label className="text-sm font-medium">System Type *<select className={control} name="systemType" value={form.systemType} onChange={change} required><option value="">Select…</option>{Object.entries(SYSTEM_TYPES).map(([v, l]) => <option key={v} value={v}>{l}</option>)}</select></label>{defaults.map(([name, label, options]) => <label key={name} className="text-sm font-medium">{label}<select className={control} name={name} value={form[name]} onChange={change}>{Object.entries(options).map(([v, l]) => <option key={v} value={v}>{l}</option>)}</select></label>)}<label className="text-sm font-medium sm:col-span-2">Description<textarea className={`${control} min-h-20`} name="description" value={form.description} onChange={change} /></label><label className="flex items-center gap-2 text-sm font-medium"><input type="checkbox" name="active" checked={form.active} onChange={change} />Active</label></div><div className="mt-4 flex justify-end"><button disabled={saving} className="inline-flex items-center gap-2 rounded-lg bg-[#b41f1f] px-4 py-2 font-semibold text-white"><Save className="h-4 w-4" />{saving ? "Saving…" : "Save Category"}</button></div></form>}
    <DataListTable rows={categories} columns={columns} emptyMessage="No demand calendar categories have been added yet." />
    <ConfirmModal open={Boolean(deleteItem)} title="Delete Category" message={`Permanently delete ${deleteItem?.name || "this category"}? Existing events keep their stored forecasting fields.`} onCancel={() => setDeleteItem(null)} onConfirm={async () => { await deleteDemandCalendarCategory(hotelUid, deleteItem.id); setDeleteItem(null); toast.success("Category deleted."); }} />
  </DemandCalendarShell>;
}
