import React, { useEffect, useMemo, useState } from "react";
import { CalendarDays, ChevronLeft, ChevronRight, List, Plus, Settings } from "lucide-react";
import { useNavigate } from "react-router-dom";
import { toast } from "react-toastify";
import DataListTable from "../shared/DataListTable";
import { useHotelContext } from "../../contexts/HotelContext";
import { DEMAND_EFFECTS, IMPACT_LEVELS, SYSTEM_TYPES } from "../../constants/demandCalendar";
import { subscribeDemandCalendarCategories, subscribeDemandCalendarEvents } from "../../services/firebaseDemandCalendar";
import DemandCalendarShell from "./DemandCalendarShell";

const badge = "inline-flex rounded-full px-2.5 py-1 text-xs font-semibold";
const dateKey = (date) => `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}-${String(date.getDate()).padStart(2, "0")}`;
export function monthGrid(month) { const first = new Date(month.getFullYear(), month.getMonth(), 1); const start = new Date(first); start.setDate(1 - ((first.getDay() + 6) % 7)); return Array.from({ length: 42 }, (_, index) => { const day = new Date(start); day.setDate(start.getDate() + index); return day; }); }

function MonthCalendar({ events, categories, month, setMonth, openEvent }) {
  const days = monthGrid(month); const today = dateKey(new Date()); const categoryNames = Object.fromEntries(categories.map((c) => [c.id, c.name]));
  return <div className="overflow-hidden rounded-xl border border-gray-200 bg-white shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3 border-b p-4"><div className="flex items-center gap-2"><button aria-label="Previous month" className="rounded border p-2 hover:bg-gray-50" onClick={() => setMonth(new Date(month.getFullYear(), month.getMonth() - 1, 1))}><ChevronLeft className="h-4 w-4" /></button><button className="rounded border px-3 py-2 text-sm font-semibold hover:bg-gray-50" onClick={() => setMonth(new Date())}>Today</button><button aria-label="Next month" className="rounded border p-2 hover:bg-gray-50" onClick={() => setMonth(new Date(month.getFullYear(), month.getMonth() + 1, 1))}><ChevronRight className="h-4 w-4" /></button></div><h2 className="text-lg font-semibold">{month.toLocaleDateString(undefined, { month: "long", year: "numeric" })}</h2></div>
    <div className="grid grid-cols-7 border-b bg-gray-50">{["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"].map((day) => <div className="p-2 text-center text-xs font-semibold uppercase text-gray-500" key={day}>{day}</div>)}</div>
    <div className="grid grid-cols-7">{days.map((day) => { const key = dateKey(day); const matches = events.filter((event) => event.startDate <= key && event.endDate >= key); return <div key={key} className={`min-h-28 border-b border-r p-1.5 ${day.getMonth() !== month.getMonth() ? "bg-gray-50 text-gray-400" : ""}`}><span className={`inline-flex h-6 w-6 items-center justify-center rounded-full text-xs ${key === today ? "bg-[#b41f1f] text-white" : ""}`}>{day.getDate()}</span><div className="mt-1 space-y-1">{matches.map((event) => <button title={`${event.name} · ${categoryNames[event.categoryId] || "Uncategorized"} · ${SYSTEM_TYPES[event.systemType] || event.systemType}`} key={event.id} onClick={() => openEvent(event.id)} className={`block w-full truncate rounded px-1.5 py-1 text-left text-[11px] font-semibold ${event.active ? "bg-red-100 text-red-900 hover:bg-red-200" : "bg-gray-200 text-gray-500 line-through"}`}>{event.name}</button>)}</div></div>; })}</div></div>;
}

export default function DemandCalendarPage() {
  const { hotelUid } = useHotelContext(); const navigate = useNavigate(); const [events, setEvents] = useState([]); const [categories, setCategories] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [view, setView] = useState("list"); const [month, setMonth] = useState(new Date()); const [filters, setFilters] = useState({ systemType: "", impactLevel: "", active: "", search: "" });
  useEffect(() => subscribeDemandCalendarCategories(hotelUid, setCategories, () => toast.error("Categories could not be loaded.")), [hotelUid]);
  useEffect(() => { setLoading(true); setError(""); return subscribeDemandCalendarEvents(hotelUid, (items) => { setEvents(items); setLoading(false); }, () => { setError("Calendar events could not be loaded."); setLoading(false); }); }, [hotelUid]);
  const categoryNames = useMemo(() => Object.fromEntries(categories.map((c) => [c.id, c.name])), [categories]);
  const visible = useMemo(() => events.filter((event) => (!filters.systemType || event.systemType === filters.systemType) && (!filters.impactLevel || event.impactLevel === filters.impactLevel) && (filters.active === "" || String(event.active) === filters.active) && (!filters.search || [event.name, event.region, categoryNames[event.categoryId]].some((v) => String(v || "").toLowerCase().includes(filters.search.toLowerCase())))), [events, filters, categoryNames]);
  const columns = [{ key: "name", label: "Event / Period Name", render: (e) => <span className="font-semibold">{e.name}</span> }, { key: "categoryId", label: "Category", render: (e) => categoryNames[e.categoryId] || "—" }, { key: "systemType", label: "System Type", render: (e) => SYSTEM_TYPES[e.systemType] || e.systemType }, { key: "startDate", label: "Start Date" }, { key: "endDate", label: "End Date" }, { key: "region", label: "Region" }, { key: "impactLevel", label: "Impact Level", render: (e) => IMPACT_LEVELS[e.impactLevel] || e.impactLevel }, { key: "groupDemandEffect", label: "Group Demand Effect", render: (e) => DEMAND_EFFECTS[e.groupDemandEffect] || e.groupDemandEffect }, { key: "active", label: "Active", render: (e) => <span className={`${badge} ${e.active ? "bg-green-100 text-green-800" : "bg-gray-100 text-gray-600"}`}>{e.active ? "Active" : "Inactive"}</span> }];
  return <DemandCalendarShell><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm uppercase tracking-wide text-gray-500">M&amp;E</p><h1 className="text-3xl font-semibold">Demand Calendar</h1><p className="mt-1 max-w-2xl text-gray-600">Manage events, holidays and other periods that may impact hotel demand.</p></div><div className="flex gap-2"><button onClick={() => navigate("/me/demand-calendar/categories")} className="inline-flex items-center gap-2 rounded-lg border bg-white px-4 py-2 font-semibold shadow-sm hover:bg-gray-50"><Settings className="h-4 w-4" />Manage Categories</button><button onClick={() => navigate("/me/demand-calendar/new")} className="inline-flex items-center gap-2 rounded-lg bg-[#b41f1f] px-4 py-2 font-semibold text-white shadow hover:bg-[#961919]"><Plus className="h-4 w-4" />Create Calendar Event</button></div></div>
    <div className="flex flex-wrap items-center justify-between gap-3"><div className="inline-flex rounded-lg border bg-white p-1"><button onClick={() => setView("list")} className={`inline-flex items-center gap-2 rounded px-3 py-2 text-sm font-semibold ${view === "list" ? "bg-gray-900 text-white" : "text-gray-600"}`}><List className="h-4 w-4" />LIST</button><button onClick={() => setView("calendar")} className={`inline-flex items-center gap-2 rounded px-3 py-2 text-sm font-semibold ${view === "calendar" ? "bg-gray-900 text-white" : "text-gray-600"}`}><CalendarDays className="h-4 w-4" />CALENDAR</button></div>
      <div className="flex flex-wrap gap-2"><input aria-label="Search events" placeholder="Search name or region…" className="rounded-lg border px-3 py-2 text-sm" value={filters.search} onChange={(e) => setFilters({ ...filters, search: e.target.value })} /><select aria-label="Filter system type" className="rounded-lg border px-3 py-2 text-sm" value={filters.systemType} onChange={(e) => setFilters({ ...filters, systemType: e.target.value })}><option value="">All system types</option>{Object.entries(SYSTEM_TYPES).map(([v, l]) => <option key={v} value={v}>{l}</option>)}</select><select aria-label="Filter impact" className="rounded-lg border px-3 py-2 text-sm" value={filters.impactLevel} onChange={(e) => setFilters({ ...filters, impactLevel: e.target.value })}><option value="">All impacts</option>{Object.entries(IMPACT_LEVELS).map(([v, l]) => <option key={v} value={v}>{l}</option>)}</select><select aria-label="Filter status" className="rounded-lg border px-3 py-2 text-sm" value={filters.active} onChange={(e) => setFilters({ ...filters, active: e.target.value })}><option value="">All statuses</option><option value="true">Active</option><option value="false">Inactive</option></select></div></div>
    {loading ? <p className="text-gray-600">Loading calendar events…</p> : error ? <div className="rounded-lg border border-red-200 bg-red-50 p-4 text-red-800">{error}</div> : view === "list" ? <DataListTable rows={visible} columns={columns} onRowClick={(event) => navigate(`/me/demand-calendar/${event.id}`)} getRowProps={(event) => ({ className: event.active ? "" : "bg-gray-50 opacity-70" })} emptyMessage="No calendar events have been added yet." /> : <MonthCalendar events={visible} categories={categories} month={month} setMonth={setMonth} openEvent={(id) => navigate(`/me/demand-calendar/${id}`)} />}
  </DemandCalendarShell>;
}
