import React, { useEffect, useState } from "react";
import { ArrowLeft, Pencil, Trash2 } from "lucide-react";
import { useNavigate, useParams } from "react-router-dom";
import { useHotelContext } from "../../contexts/HotelContext";
import { DEMAND_EFFECTS, IMPACT_LEVELS, SYSTEM_TYPES } from "../../constants/demandCalendar";
import { deleteDemandCalendarEvent, getDemandCalendarEvent, subscribeDemandCalendarCategories } from "../../services/firebaseDemandCalendar";
import { Card } from "../layout/Card";
import ConfirmModal from "../layout/ConfirmModal";
import DemandCalendarShell from "./DemandCalendarShell";

function Item({ label, children }) { return <div><dt className="text-xs font-semibold uppercase tracking-wide text-gray-500">{label}</dt><dd className="mt-1 font-medium text-gray-900">{children || "—"}</dd></div>; }
export default function DemandCalendarEventDetailPage() {
  const { hotelUid } = useHotelContext(); const { eventId } = useParams(); const navigate = useNavigate(); const [event, setEvent] = useState(null); const [categories, setCategories] = useState([]); const [loading, setLoading] = useState(true); const [confirmDelete, setConfirmDelete] = useState(false);
  useEffect(() => subscribeDemandCalendarCategories(hotelUid, setCategories), [hotelUid]);
  useEffect(() => { if (hotelUid) getDemandCalendarEvent(hotelUid, eventId).then((item) => { setEvent(item); setLoading(false); }); }, [hotelUid, eventId]);
  const category = categories.find((item) => item.id === event?.categoryId);
  return <DemandCalendarShell><div className="flex items-center justify-between gap-3"><div className="flex items-center gap-3"><button onClick={() => navigate("/me/demand-calendar")} className="rounded-lg border bg-white p-2"><ArrowLeft className="h-5 w-5" /></button><div><p className="text-sm uppercase tracking-wide text-gray-500">M&amp;E / Demand Calendar</p><h1 className="text-3xl font-semibold">Calendar Event Detail</h1></div></div>{event && <div className="flex gap-2"><button onClick={() => navigate(`/me/demand-calendar/${eventId}/edit`)} className="rounded-lg bg-[#b41f1f] p-2 text-white" title="Edit Calendar Event"><Pencil className="h-5 w-5" /></button><button onClick={() => setConfirmDelete(true)} className="rounded-lg border border-red-200 bg-white p-2 text-red-700" title="Permanently Delete Calendar Event"><Trash2 className="h-5 w-5" /></button></div>}</div>
    {loading ? <p>Loading calendar event…</p> : !event ? <Card>Calendar event not found.</Card> : <div className="space-y-5"><Card><h2 className="mb-4 text-lg font-semibold">Event Information</h2><dl className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3"><Item label="Event / Period Name">{event.name}</Item><Item label="Category">{category?.name}</Item><Item label="System Type">{SYSTEM_TYPES[event.systemType]}</Item><Item label="Start Date">{event.startDate}</Item><Item label="End Date">{event.endDate}</Item><Item label="Region / Market">{event.region}</Item><Item label="Venue">{event.venue}</Item></dl></Card>
      <Card><h2 className="mb-4 text-lg font-semibold">Demand Impact</h2><dl className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3"><Item label="Impact Level">{IMPACT_LEVELS[event.impactLevel]}</Item><Item label="Group Demand Effect">{DEMAND_EFFECTS[event.groupDemandEffect]}</Item><Item label="Business Transient Effect">{DEMAND_EFFECTS[event.transientBusinessEffect]}</Item><Item label="Leisure Transient Effect">{DEMAND_EFFECTS[event.transientLeisureEffect]}</Item><Item label="Banqueting Demand Effect">{DEMAND_EFFECTS[event.bqtDemandEffect]}</Item><Item label="Confidence">{IMPACT_LEVELS[event.confidence]}</Item></dl></Card>
      <Card><h2 className="mb-4 text-lg font-semibold">Additional Information</h2><dl className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3"><Item label="Expected Attendance">{event.expectedAttendance === null ? "—" : event.expectedAttendance}</Item><Item label="Source">{event.source}</Item><Item label="Source URL">{event.sourceUrl && <a className="text-blue-700 underline" href={event.sourceUrl} target="_blank" rel="noreferrer">{event.sourceUrl}</a>}</Item><Item label="Active"><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${event.active ? "bg-green-100 text-green-800" : "bg-gray-100 text-gray-600"}`}>{event.active ? "Active" : "Inactive"}</span></Item><div className="sm:col-span-2 lg:col-span-3"><Item label="Notes">{event.notes}</Item></div></dl></Card></div>}
    <ConfirmModal open={confirmDelete} title="Delete Calendar Event" message={`Permanently delete ${event?.name || "this event"}? Deactivating it in Edit is preferred for audit history.`} onCancel={() => setConfirmDelete(false)} onConfirm={async () => { await deleteDemandCalendarEvent(hotelUid, eventId); navigate("/me/demand-calendar"); }} />
  </DemandCalendarShell>;
}
