import React from "react";
import { Card } from "../layout/Card";
import MarketPricingContext from "./MarketPricingContext";

const money = (value) => value === null || value === undefined ? "Unavailable" : `€${Number(value).toFixed(2)}`;
const rooms = (value) => value === null || value === undefined ? "—" : Math.round(value).toLocaleString();
const percent = (value) => value === null || value === undefined ? "—" : `${(Number(value) * 100).toFixed(1)}%`;
const criticalWarning = (warning) => warning.code === "ECONOMIC_FLOOR_ABOVE_MARKET" || /unavailable|required valuation/i.test(warning.message || "");

function Metric({ label, value, prominent = false, helper, tone = "neutral" }) {
  const styles = prominent ? "border-[#b41f1f] bg-red-50 lg:scale-[1.02]" : tone === "secondary" ? "border-indigo-200 bg-indigo-50" : "border-gray-200 bg-gray-50";
  return <div className={`rounded-xl border-2 p-5 ${styles}`}><p className="text-xs font-bold uppercase tracking-widest text-gray-600">{label}</p><p className={`${prominent ? "text-4xl" : "text-3xl"} mt-2 font-bold text-gray-900`}>{value}</p>{helper && <p className="mt-2 text-sm font-medium text-gray-600">{helper}</p>}</div>;
}

function ObservationTable({ label, observations, kind }) {
  if (!observations?.length) return null;
  const transient = kind === "transient";
  return <details className="mt-4 rounded-lg border border-gray-200"><summary className="cursor-pointer p-3 text-sm font-semibold">View {observations.length} historical ADR observations</summary><div className="overflow-x-auto border-t"><table className="min-w-full text-xs"><thead><tr className="text-left text-gray-500">{["Date", transient ? "Transient Rooms" : "Group Rooms", "Deductible Revenue", "Raw ADR", "Inflation-adjusted ADR"].map((heading) => <th className="p-2" key={heading}>{heading}</th>)}</tr></thead><tbody>{observations.map((item) => <tr className="border-t" key={item.date}><td className="p-2">{item.date}</td><td className="p-2">{rooms(transient ? item.individualRooms : item.groupRooms)}</td><td className="p-2">{money(transient ? item.individualRevenueDeductible : item.groupRevenueDeductible)}</td><td className="p-2">{money(transient ? item.rawTransientAdrExVat : item.rawGroupAdrExVat)}</td><td className="p-2">{money(transient ? item.inflationAdjustedTransientAdrExVat : item.inflationAdjustedGroupAdrExVat)}</td></tr>)}</tbody></table></div><span className="sr-only">{label}</span></details>;
}

export default function GroupQuoteAnalysisView({ contribution, forecastData, groupForecastData, marketContextSnapshot, pricingGuidance, quoteSettings, testGroupRate, setTestGroupRate, simulation, targetSimulation, forecastLoading }) {
  if (!contribution || contribution.validationError) return contribution?.validationError ? <Card className="border border-red-200 bg-red-50 text-red-800"><strong>Contribution settings error:</strong> {contribution.validationError}</Card> : null;
  const market = marketContextSnapshot?.groupStaySummary || {};
  const warnings = [...(contribution.warningDetails || []), ...(pricingGuidance?.warnings || []), ...(marketContextSnapshot?.warnings || [])].filter((warning, index, all) => all.findIndex((item) => item.code === warning.code) === index);
  const critical = warnings.filter(criticalWarning);
  const notes = warnings.filter((warning) => !criticalWarning(warning));

  return <div className="space-y-6">
    <Card className="overflow-hidden border border-gray-200 bg-white p-0 shadow-sm" aria-labelledby="commercial-decision-title">
      <header className="border-b border-red-100 bg-red-50 px-5 py-4"><p className="text-xs font-semibold uppercase tracking-widest text-[#b41f1f]">Level 1 · Decision</p><h2 id="commercial-decision-title" className="mt-1 text-2xl font-semibold">Commercial Decision</h2><p className="mt-1 text-sm text-gray-600">Quote corridor and the commercial context behind it.</p></header>
      <div className="grid gap-4 p-5 lg:grid-cols-[1.2fr_1fr_1fr]">
        <Metric prominent label="Target Rate" value={money(pricingGuidance?.targetRateInclVat)} helper={`${pricingGuidance?.proposedRateMealBasis || "—"} incl. VAT · Suggested starting quote`} />
        <Metric tone="secondary" label="Stretch Rate" value={money(pricingGuidance?.stretchRateInclVat)} helper={`${pricingGuidance?.proposedRateMealBasis || "—"} incl. VAT · Upper negotiation anchor`} />
        <Metric label="Economic Floor" value={money(contribution.economicFloorRateInclVat)} helper={`${pricingGuidance?.proposedRateMealBasis || "—"} incl. VAT · Economic protection threshold`} />
      </div>
      <p className="px-5 text-sm text-gray-600">Do not quote below the Economic Floor without a deliberate strategic override.</p>
      <dl className="grid gap-x-6 gap-y-3 p-5 text-sm sm:grid-cols-2 lg:grid-cols-3">{[
        ["Expected incremental contribution", targetSimulation ? `${targetSimulation.netIncrementalContribution > 0 ? "+" : ""}${money(targetSimulation.netIncrementalContribution)}` : "—"],
        ["Displacement", percent(pricingGuidance?.displacementRatio)], ["Market anchor", money(pricingGuidance?.marketAnchorInclVat)],
        ["Own public rate", money(market.weightedOwnPublicRateInclVat)], ["Market Demand", percent(pricingGuidance?.weightedMarketDemand)], ["Guidance confidence", pricingGuidance?.confidence || "Unavailable"],
      ].map(([label, value]) => <div className="flex justify-between gap-3 border-b border-gray-100 pb-2" key={label}><dt className="text-gray-600">{label}</dt><dd className={`font-semibold ${label === "Expected incremental contribution" && targetSimulation?.netIncrementalContribution >= 0 ? "text-green-700" : ""}`}>{value}</dd></div>)}</dl>
      {critical.map((warning) => <div role="alert" data-warning-severity="critical" className="mx-5 mb-3 rounded-lg border-2 border-red-300 bg-red-50 p-3 text-sm text-red-900" key={warning.code}><strong>Action required · {warning.code}</strong><p>{warning.message}</p></div>)}
      {notes.length > 0 && <details className="mx-5 mb-4 rounded-lg border border-gray-200 bg-gray-50"><summary className="cursor-pointer p-3 text-sm font-semibold">{notes.length} modelling {notes.length === 1 ? "note" : "notes"} · View details</summary><ul className="ml-8 list-disc space-y-1 px-3 pb-3 text-sm text-gray-700">{notes.map((warning) => <li key={warning.code}><span className="font-medium">Informational:</span> {warning.message}</li>)}</ul></details>}
      <details className="border-t border-gray-200"><summary className="cursor-pointer px-5 py-4 font-semibold">Test another rate</summary><div className="border-t bg-gray-50 p-5"><p className="text-sm text-gray-600">Simulation only; the tested value is not saved as the quote rate.</p><label className="mt-3 block max-w-md text-sm font-semibold">Test Average Group Rate (incl. VAT)<input min="0" step="0.01" type="number" value={testGroupRate} onChange={(event) => setTestGroupRate(event.target.value)} className="mt-2 w-full rounded-lg border border-gray-300 px-3 py-2 font-normal" /></label>{simulation && <dl className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{[["Difference vs Target", pricingGuidance?.targetRateInclVat == null ? "—" : money(simulation.testGroupRateInclVat - pricingGuidance.targetRateInclVat)], ["Difference vs Floor", money(simulation.rateAboveFloor)], ["Net incremental contribution", money(simulation.netIncrementalContribution)], ["Commission cost", money(simulation.testGroupCommissionCost)], ["Group contribution", money(simulation.testGroupContribution)]].map(([label, value]) => <div className="rounded bg-white p-3" key={label}><dt className="text-xs uppercase text-gray-500">{label}</dt><dd className="font-semibold">{value}</dd></div>)}</dl>}</div></details>
    </Card>

    <section aria-labelledby="group-impact-title"><h2 id="group-impact-title" className="text-xl font-semibold">Key Group Impact</h2><dl className="mt-3 grid gap-3 grid-cols-2 lg:grid-cols-4">{[["Requested RN", rooms(contribution.totalRequestedGroupRoomNights)], ["Displaced RN", rooms(contribution.totalDisplacedRooms)], ["Incremental RN", rooms(contribution.totalNonDisplacingGroupRooms)], ["Displacement Ratio", percent(contribution.totalDisplacedRooms / contribution.totalRequestedGroupRoomNights)]].map(([label, value]) => <Card className="border p-4 shadow-sm" key={label}><dt className="text-xs font-semibold uppercase text-gray-500">{label}</dt><dd className="mt-1 text-2xl font-semibold">{value}</dd></Card>)}</dl><p className="mt-3 text-sm text-gray-600">Base scenario: <strong>{rooms(contribution.scenarioTotals.base.displacedFutureTransientRooms)}</strong> transient RN + <strong>{rooms(contribution.scenarioTotals.base.displacedFutureGroupRooms)}</strong> future group RN displaced.</p></section>

    <Card className="overflow-hidden border bg-white p-0 shadow-sm"><header className="px-5 py-4"><p className="text-xs font-semibold uppercase tracking-widest text-gray-500">Level 2 · Operational detail</p><h2 className="mt-1 text-xl font-semibold">Nightly Pricing</h2></header><div className="overflow-x-auto border-t"><table className="min-w-[800px] w-full text-sm"><thead className="bg-gray-50 text-left text-xs uppercase text-gray-500"><tr>{["Date", "Rooms", "Economic Floor", "Displacement %", "Own Public Rate", "Market Reference", "Market Demand", "Details"].map((h) => <th className="px-3 py-3" key={h}>{h}</th>)}</tr></thead><tbody>{contribution.nightly.map((night) => { const base = night.scenarios.base; const marketNight = marketContextSnapshot?.stayDates?.find((row) => row.stayDate === night.stayDate); const group = groupForecastData?.byDate?.[night.stayDate] || {}; return <React.Fragment key={night.stayDate}><tr className="border-t"><td className="px-3 py-3 font-medium">{night.stayDate}</td><td className="px-3 py-3">{rooms(night.requestedGroupRooms)}</td><td className="px-3 py-3">{money(contribution.economicFloorRateInclVat)}</td><td className="px-3 py-3">{percent(night.requestedGroupRooms ? base.totalDisplacedFutureRooms / night.requestedGroupRooms : null)}</td><td className="px-3 py-3">{money(marketNight?.ownPublicRateInclVat)}</td><td className="px-3 py-3">{money(marketNight?.weightedCompsetReferenceInclVat)}</td><td className="px-3 py-3">{percent(marketNight?.marketDemand)}</td><td className="px-3 py-3"><details><summary className="cursor-pointer whitespace-nowrap font-semibold">Technical details</summary><dl className="mt-3 grid min-w-[32rem] grid-cols-2 gap-2 rounded bg-gray-50 p-3 text-xs">{[["Final transient forecast", rooms(night.finalTransientDemandForecast)], ["Final group forecast", rooms(group.forecastBase)], ["Future group potential", rooms(night.futureGroupDemandBase)], ["Displaced transient RN", rooms(base.displacedFutureTransientRooms)], ["Displaced future group RN", rooms(base.displacedFutureGroupRooms)], ["Incremental RN", rooms(base.nonDisplacingGroupRooms)], ["Lost contribution", money(base.totalLostContribution)], ["Confidence", group.confidence || "—"], ["Sellable inventory", rooms(night.sellableInventory)], ["Capacity conflict", rooms(night.capacityConflictRooms)]].map(([label, value]) => <div key={label}><dt className="text-gray-500">{label}</dt><dd className="font-medium">{value}</dd></div>)}</dl></details></td></tr></React.Fragment>; })}</tbody></table></div></Card>

    <MarketPricingContext snapshot={marketContextSnapshot} />

    <details className="rounded-lg border border-gray-200 bg-white shadow-sm"><summary className="cursor-pointer p-4 text-lg font-semibold">How is the Economic Floor calculated?</summary><div className="grid gap-5 border-t p-5 md:grid-cols-2 xl:grid-cols-4">
      <section><p className="text-xs font-semibold uppercase text-gray-500">1 · Opportunity Cost</p><dl className="mt-3 space-y-2 text-sm">{[["Lost future transient contribution", contribution.totalLostFutureTransientContribution], ["Lost future group contribution", contribution.totalLostFutureGroupContribution], ["Total opportunity cost", contribution.totalLostContribution]].map(([l,v])=><div className="flex justify-between gap-3" key={l}><dt>{l}</dt><dd>{money(v)}</dd></div>)}</dl></section>
      <section><p className="text-xs font-semibold uppercase text-gray-500">2 · New Group Costs / Offsets</p><dl className="mt-3 space-y-2 text-sm">{[["Group variable room costs", contribution.groupVariableRoomCosts], ["Group breakfast costs", contribution.groupBreakfastCosts], ["BQT contribution", contribution.bqtContribution], ["Required revenue after costs", contribution.requiredRoomRevenueAfterCostsExVat]].map(([l,v])=><div className="flex justify-between gap-3" key={l}><dt>{l}</dt><dd>{money(v)}</dd></div>)}</dl></section>
      <section><p className="text-xs font-semibold uppercase text-gray-500">3 · Commission</p><dl className="mt-3 space-y-2 text-sm"><div className="flex justify-between"><dt>Group commission</dt><dd>{percent(contribution.groupCommission)}</dd></div><div className="flex justify-between gap-3"><dt>Required commissionable revenue</dt><dd>{money(contribution.requiredCommissionableRoomRevenueExVat)}</dd></div></dl></section>
      <section><p className="text-xs font-semibold uppercase text-gray-500">4 · VAT / Commercial Floor</p><dl className="mt-3 space-y-2 text-sm">{[["Economic Floor excl. VAT", money(contribution.economicFloorRateExVat)], ["Room VAT", `${Number(contribution.roomVatPercentage).toFixed(1)}%`], ["Economic Floor incl. VAT", money(contribution.economicFloorRateInclVat)]].map(([l,v])=><div className="flex justify-between gap-3" key={l}><dt>{l}</dt><dd className="font-semibold">{v}</dd></div>)}</dl></section>
    </div></details>

    <details className="rounded-lg border border-gray-200 bg-white shadow-sm"><summary className="cursor-pointer p-4 text-lg font-semibold">Model Diagnostics <span className="ml-2 text-sm font-normal text-gray-500">4 models · View details</span></summary><div className="space-y-3 border-t bg-gray-50 p-4"><p className="text-xs font-semibold uppercase tracking-widest text-gray-500">Level 3 · Full audit trail</p>
      <details className="rounded-lg border bg-white"><summary className="grid cursor-pointer gap-2 p-4 sm:grid-cols-[1fr_auto_auto_auto] sm:items-center"><strong>Transient Demand</strong><span>{rooms(Object.values(forecastData?.byDate || {})[0]?.transientDemandForecast)} RN</span><span>{Object.values(forecastData?.byDate || {})[0]?.forecastConfidence || "—"} confidence</span><span>{Object.values(forecastData?.byDate || {})[0]?.historicalSelectedCount || 0} comparables · View details</span></summary><div className="space-y-3 border-t p-4">{Object.values(forecastData?.byDate || {}).map((result)=><section className="rounded border p-3" key={result.stayDate}><h3 className="font-semibold">{result.stayDate}</h3><dl className="mt-2 grid gap-2 text-sm sm:grid-cols-2 lg:grid-cols-4">{[["Historical selection tier",result.historicalSelectionTier],["Selected years",result.historicalYears?.join(", ")||"None"],["Sample size",result.historicalSelectedCount],["Lighthouse adjustment",`${result.lighthouseMarketModifier?.toFixed(3)}×`],["Current OTB",rooms(result.currentTransientOtb)],["Final forecast",rooms(result.transientDemandForecast)],["Confidence",result.forecastConfidence]].map(([l,v])=><div key={l}><dt className="text-gray-500">{l}</dt><dd>{v}</dd></div>)}</dl>{result.warnings?.length > 0 && <p className="mt-2 text-sm text-amber-800">Warning: {result.warnings.join(" ")}</p>}<ObservationTable label="Transient Demand comparables" observations={result.historicalTransientAdrObservations} kind="transient" /></section>)}</div></details>
      <details className="rounded-lg border bg-white"><summary className="grid cursor-pointer gap-2 p-4 sm:grid-cols-[1fr_auto_auto_auto] sm:items-center"><strong>Group Demand</strong><span>{rooms(Object.values(groupForecastData?.byDate || {})[0]?.forecastBase)} RN</span><span>{Object.values(groupForecastData?.byDate || {})[0]?.confidence || "—"} confidence</span><span>{Object.values(groupForecastData?.byDate || {})[0]?.sampleSize || 0} comparables · View details</span></summary><div className="space-y-3 border-t p-4">{Object.values(groupForecastData?.byDate || {}).map((result)=><section className="rounded border p-3" key={result.stayDate}><h3 className="font-semibold">{result.stayDate}</h3><dl className="mt-2 grid gap-2 text-sm sm:grid-cols-2 lg:grid-cols-4">{[["Current Group OTB",rooms(result.currentGroupOtb)],["P25 / P50 / P75",`${rooms(result.historicalP25GroupRooms)} / ${rooms(result.historicalP50GroupRooms)} / ${rooms(result.historicalP75GroupRooms)}`],["Remaining group potential",rooms(result.remainingPotentialBase)],["Tier",result.comparableTier],["Calendar context",result.targetCalendarFeatures?.calendarRegime?.join(", ")],["Sample",result.sampleSize],["Confidence",result.confidence]].map(([l,v])=><div key={l}><dt className="text-gray-500">{l}</dt><dd>{v}</dd></div>)}</dl><details className="mt-3 rounded border"><summary className="cursor-pointer p-3 text-sm font-semibold">View {result.comparables?.length || 0} historical comparables</summary>{result.comparables?.length > 0 && <div className="overflow-x-auto border-t"><table className="min-w-full text-xs"><thead><tr>{["Date","DOW","Calendar Context","Final Group Rooms","Sellable Inventory"].map(h=><th className="p-2 text-left" key={h}>{h}</th>)}</tr></thead><tbody>{result.comparables.map(item=><tr className="border-t" key={item.stayDate}><td className="p-2">{item.stayDate}</td><td className="p-2">{item.dayOfWeek}</td><td className="p-2">{item.calendarContext}</td><td className="p-2">{rooms(item.finalGroupRooms)}</td><td className="p-2">{rooms(item.sellableInventory)}</td></tr>)}</tbody></table></div>}</details></section>)}</div></details>
      {[["Transient Value", "transient"], ["Future Group Value", "group"]].map(([title, kind]) => { const night = contribution.nightly[0] || {}; const transient = kind === "transient"; return <details className="rounded-lg border bg-white" key={title}><summary className="grid cursor-pointer gap-2 p-4 sm:grid-cols-[1fr_auto_auto_auto] sm:items-center"><strong>{title}</strong><span>{money(transient ? night.expectedFutureTransientRoomRateExVat : night.expectedFutureGroupRoomRateExVat)} excl VAT</span><span>{transient ? night.transientValueConfidence : night.futureGroupValueConfidence || "—"} confidence</span><span>{transient ? night.historicalTransientAdrEvidenceCount : night.historicalAdrEvidenceCount} ADR observations · View details</span></summary><div className="space-y-3 border-t p-4">{contribution.nightly.map((item)=><section className="rounded border p-3" key={item.stayDate}><h3 className="font-semibold">{item.stayDate}</h3><dl className="mt-2 grid gap-2 text-sm sm:grid-cols-2 lg:grid-cols-4">{(transient ? [["Historical Comparable Transient ADR",money(item.historicalComparableTransientAdrExVat)],["Current Transient OTB ADR",money(item.currentTransientOtbAdrExVat)],["Expected Future Transient ADR",money(item.expectedFutureTransientRoomRateExVat)],["Distribution Cost",percent(Number(quoteSettings.transientDistributionCostPercentage||0)/100)],["Room Contribution / RN",money(item.transientRoomContributionPerRoom)],["Breakfast Contribution / RN",money(item.transientBreakfastContributionPerRoom)],["Total Contribution / RN",money(item.futureTransientContributionPerRoom)],["Value Confidence",item.transientValueConfidence]] : [["Historical Comparable Group ADR",money(item.historicalComparableGroupAdrExVat)],["Current Existing Group ADR",money(item.currentExistingGroupAdrExVat)],["Expected Future Group ADR",money(item.expectedFutureGroupRoomRateExVat)],["Future Group Commission",percent(item.expectedFutureGroupCommission)],["Future Group Contribution / RN",money(item.futureGroupContributionPerRoom)],["Value Confidence",item.futureGroupValueConfidence],["Pipeline commercial context",item.hasPipelineCommercialRate?money(item.pipelineCommercialRate):"—"]]).map(([l,v])=><div key={l}><dt className="text-gray-500">{l}</dt><dd>{v}</dd></div>)}</dl><ObservationTable label={`${title} observations`} observations={transient ? item.historicalTransientAdrObservations : item.historicalGroupAdrObservations} kind={kind} /></section>)}</div></details>; })}
      {forecastLoading && <p className="text-sm text-gray-500">Loading forecast…</p>}
    </div></details>
  </div>;
}
