import React from "react";
import { Card } from "../layout/Card";
import { formatHotelStayDate } from "../../utils/hotelStayDates";

const money = (value) => value === null || value === undefined ? "—" : `€${Number(value).toFixed(2)}`;
const percent = (value) => value === null || value === undefined ? "—" : `${(Number(value) * 100).toFixed(1)}%`;
const statusLabel = { AVAILABLE: "AVAILABLE", SOLD_OUT: "SOLD OUT", LOS_RESTRICTION: "LOS RESTRICTION", CLOSED: "CLOSED", UNAVAILABLE: "UNAVAILABLE", PLACEHOLDER_RATE: "PLACEHOLDER RATE" };
const statusStyle = { AVAILABLE: "bg-green-100 text-green-800", SOLD_OUT: "bg-amber-100 text-amber-900", LOS_RESTRICTION: "bg-purple-100 text-purple-800", PLACEHOLDER_RATE: "bg-blue-100 text-blue-800", CLOSED: "bg-gray-200 text-gray-800", UNAVAILABLE: "bg-red-100 text-red-800" };

export default function MarketPricingContext({ snapshot, stale = false }) {
  if (!snapshot) return <Card><h2 className="text-xl font-semibold">Market Pricing Context</h2><p className="mt-2 text-sm text-gray-600">Market pricing context is unavailable. Configure a compset and run the analysis.</p></Card>;
  const summary = snapshot.groupStaySummary || {};
  return <Card className={`border bg-white p-0 shadow-sm ${stale ? "border-amber-300" : "border-gray-200"}`}>
    <header className="border-b px-5 py-4"><p className="text-xs font-semibold uppercase tracking-widest text-gray-500">Level 2 · Operational detail</p><h2 className="mt-1 text-xl font-semibold">Market Pricing Context</h2><p className="mt-1 text-sm text-gray-600">Public Lighthouse prices include VAT and are informational only. Snapshot {snapshot.lighthouseSnapshotDate || "unavailable"}.</p>{stale && <p className="mt-2 font-semibold text-amber-800">This snapshot belongs to the stale analysis and is historical.</p>}</header>
    {summary.marketDateCoverage != null && summary.marketDateCoverage < 1 && <div className="mx-5 mt-4 rounded border border-amber-300 bg-amber-50 p-3 font-semibold">PARTIAL_MARKET_DATE_COVERAGE — Public market context is available for {percent(summary.marketDateCoverage)} of requested room nights.</div>}
    <dl className="grid gap-3 p-5 grid-cols-2 lg:grid-cols-3">{[["Weighted Own Public Rate", money(summary.weightedOwnPublicRateInclVat)], ["Weighted Market Reference", money(summary.weightedMarketReferenceInclVat)], ["Weighted Compset Median", money(summary.weightedCompsetMedianInclVat)], ["Coverage", percent(summary.rateCoverage)], ["Sold-out pressure", percent(summary.weightedSoldOutWeightShare)], ["Placeholder share", percent(summary.weightedPlaceholderWeightShare)]].map(([label,value])=><div className="rounded-lg bg-gray-50 p-3" key={label}><dt className="text-xs uppercase text-gray-500">{label}</dt><dd className="mt-1 text-lg font-semibold">{value}</dd></div>)}</dl>
    <div className="space-y-2 border-t bg-gray-50 p-4">{snapshot.stayDates?.map((date)=><article className="rounded-lg border bg-white" key={date.stayDate}><div className="grid gap-3 p-4 text-sm sm:grid-cols-3 lg:grid-cols-6"><strong>{formatHotelStayDate(date.stayDate)}</strong>{date.lighthouseDataStatus !== "AVAILABLE" && <span className="font-semibold text-amber-800 sm:col-span-2 lg:col-span-5">{date.lighthouseDataStatus === "OUT_OF_HORIZON" ? "Unavailable — outside current Lighthouse stay-date horizon" : "Unavailable — expected Lighthouse record is missing"}{snapshot.lighthouseCoverage?.maximumStayDateAvailable && <> · Latest snapshot covers through {formatHotelStayDate(snapshot.lighthouseCoverage.maximumStayDateAvailable)}</>}</span>}<span>Own <strong>{money(date.ownPublicRateInclVat)}</strong></span><span>Market <strong>{money(date.weightedCompsetReferenceInclVat)}</strong></span><span>Demand <strong>{percent(date.marketDemand)}</strong></span><span>Coverage <strong>{percent(date.coverage)}</strong></span><span>Sold-out pressure <strong>{percent(date.soldOutWeightShare)}</strong></span></div><details className="border-t"><summary className="cursor-pointer px-4 py-3 text-sm font-semibold">View compset details</summary><div className="overflow-x-auto border-t"><table className="min-w-[680px] w-full text-xs"><thead><tr className="text-left text-gray-500">{["Competitor","Public Rate / Status","Configured Weight","Effective Weight","Availability Status"].map(h=><th className="p-3" key={h}>{h}</th>)}</tr></thead><tbody>{date.competitors?.map((competitor)=><tr className="border-t" key={competitor.competitorId}><td className="p-3 font-medium">{competitor.displayName}</td><td className="p-3">{["AVAILABLE","PLACEHOLDER_RATE"].includes(competitor.availabilityStatus) ? money(competitor.availabilityStatus === "AVAILABLE" ? competitor.publicRateInclVat : competitor.displayRateInclVat) : statusLabel[competitor.availabilityStatus]}</td><td className="p-3">{competitor.configuredWeight}</td><td className="p-3">{percent(competitor.normalizedEffectiveWeight)}</td><td className="p-3"><span className={`rounded-full px-2 py-1 font-semibold ${statusStyle[competitor.availabilityStatus] || statusStyle.UNAVAILABLE}`}>{statusLabel[competitor.availabilityStatus] || competitor.availabilityStatus}</span></td></tr>)}</tbody></table></div></details></article>)}</div>
  </Card>;
}
