import React from "react";
import { Card } from "../layout/Card";

const money = (value) => value === null || value === undefined ? "Unavailable" : `€${Number(value).toFixed(2)}`;
const percent = (value) => value === null || value === undefined ? "—" : `${(Number(value) * 100).toFixed(1)}%`;
const points = (value) => `${value > 0 ? "+" : ""}${(Number(value) * 100).toFixed(1)} pts`;

export default function PricingGuidance({ guidance, ownPublicRateInclVat }) {
  if (!guidance) return null;
  const basis = guidance.proposedRateMealBasis;
  const difference = (rate) => rate === null || ownPublicRateInclVat === null ? "—" : `${rate - ownPublicRateInclVat >= 0 ? "+" : ""}${money(rate - ownPublicRateInclVat)}`;
  return <Card className="overflow-hidden border border-indigo-200 bg-white p-0 shadow-sm">
    <div className="border-b border-indigo-100 bg-indigo-50 px-6 py-4"><p className="text-xs font-semibold uppercase tracking-widest text-indigo-700">Rule-based pricing guidance</p><h3 className="mt-1 text-xl font-semibold">Commercial pricing range</h3><p className="mt-1 text-sm text-gray-600">Economic Floor, displacement and public market conditions. This is deterministic guidance, not an optimal-rate or competitor group-rate prediction.</p></div>
    <div className="grid gap-4 p-6 md:grid-cols-3">{[["Economic Floor", guidance.economicFloorRateInclVat], ["Target Rate", guidance.targetRateInclVat], ["Stretch Rate", guidance.stretchRateInclVat]].map(([label, value], index) => <div key={label} className={`rounded-xl border p-5 ${index === 0 ? "border-blue-200 bg-blue-50" : "border-indigo-200 bg-indigo-50"}`}><p className="text-xs font-bold uppercase tracking-wide">{label}</p><p className="mt-1 text-3xl font-bold">{money(value)}</p><p className="text-sm font-semibold">{basis} incl. VAT</p>{index > 0 && <p className="mt-2 text-xs text-gray-600">Vs Own Public Rate: {difference(value)}</p>}</div>)}</div>
    <div className="px-6 pb-4"><p className="text-sm"><strong>Guidance confidence:</strong> {guidance.confidence}</p>{guidance.warnings.map((warning) => <p key={warning.code} className={`mt-2 rounded border p-3 text-sm ${warning.code === "ECONOMIC_FLOOR_ABOVE_MARKET" ? "border-amber-300 bg-amber-50 text-amber-900 font-semibold" : "border-gray-200 bg-gray-50 text-gray-700"}`}><strong>{warning.code}:</strong> {warning.message}</p>)}</div>
    <details className="border-t border-gray-200"><summary className="cursor-pointer px-6 py-4 font-semibold">How was this pricing range calculated?</summary><dl className="grid gap-3 border-t border-gray-100 p-6 text-sm sm:grid-cols-2 lg:grid-cols-3">{[["Economic Floor", money(guidance.economicFloorRateInclVat)], ["Market Anchor", `${money(guidance.marketAnchorInclVat)} · ${guidance.marketAnchorSource}`], ["Displacement Ratio", percent(guidance.displacementRatio)], ["Yield Band", guidance.yieldBand], ["Base Target Capture", percent(guidance.baseTargetCapture)], ["Base Stretch Capture", percent(guidance.baseStretchCapture)], ["High Demand Adjustment", points(guidance.demandAdjustment)], ["Sold-out Adjustment", points(guidance.soldOutAdjustment)], ["Final Target Capture", percent(guidance.targetCapture)], ["Final Stretch Capture", percent(guidance.stretchCapture)], ["Raw Target", money(guidance.rawTargetRateInclVat)], ["Raw Stretch", money(guidance.rawStretchRateInclVat)], ["Final Target", money(guidance.targetRateInclVat)], ["Final Stretch", money(guidance.stretchRateInclVat)]].map(([label, value]) => <div key={label}><dt className="text-gray-500">{label}</dt><dd className="font-semibold">{value}</dd></div>)}</dl></details>
  </Card>;
}
