import React, { useState } from "react";
import { DECLINED_REASONS, LOST_REASONS, QUOTE_STATUSES, saveQuoteOutcome } from "../../services/firebaseQuotes";

const opts = (values) => values.map((value) => <option key={value} value={value}>{value.replaceAll("_", " ")}</option>);
export default function QuoteOutcomeForm({ hotelUid, quote, competitors, onSaved }) {
  const existing = quote.outcome || {};
  const [form, setForm] = useState({ status: existing.status || quote.commercialStatus || "PENDING", finalQuotedRateInclVat: existing.finalQuotedRateInclVat ?? "", finalQuotedMealBasis: existing.finalQuotedMealBasis || quote.pricingGuidanceSnapshot?.proposedRateMealBasis || "UNKNOWN", lostReason: existing.lostReason || "UNKNOWN", declinedReason: existing.declinedReason || "OTHER", lostToCompetitorId: existing.lostToCompetitorId || "", competitorQuotedRateInclVat: existing.competitorQuotedRateInclVat ?? "", competitorMealBasis: existing.competitorMealBasis || "UNKNOWN", competitorOccupancyBasis: existing.competitorOccupancyBasis || "UNKNOWN", competitorSourceConfidence: existing.competitorSourceConfidence || "LOW", notes: existing.notes || "", rateNotes: "" });
  const [saving,setSaving]=useState(false); const [message,setMessage]=useState("");
  const set=(key,value)=>setForm((current)=>({...current,[key]:value}));
  const submit=async(e)=>{e.preventDefault();setSaving(true);setMessage("");try{await saveQuoteOutcome(hotelUid,quote,{...form,competitors});setMessage("Outcome and commercial evidence saved.");onSaved?.();}catch(err){setMessage(err.message);}finally{setSaving(false);}};
  return <form onSubmit={submit} className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3"><label className="text-sm font-semibold">Status<select value={form.status} onChange={(e)=>set("status",e.target.value)} className="mt-1 w-full rounded border p-2">{opts(QUOTE_STATUSES)}</select></label><label className="text-sm font-semibold">Final Quoted Rate incl. VAT<input min="0" step=".01" type="number" value={form.finalQuotedRateInclVat} onChange={(e)=>set("finalQuotedRateInclVat",e.target.value)} className="mt-1 w-full rounded border p-2" /></label><label className="text-sm font-semibold">Final Meal Basis<select value={form.finalQuotedMealBasis} onChange={(e)=>set("finalQuotedMealBasis",e.target.value)} className="mt-1 w-full rounded border p-2">{opts(["RO","BB","MIXED","OTHER","UNKNOWN"])}</select></label>
  {form.status==="LOST"&&<><label className="text-sm font-semibold">Lost Reason<select value={form.lostReason} onChange={(e)=>set("lostReason",e.target.value)} className="mt-1 w-full rounded border p-2">{opts(LOST_REASONS)}</select></label><label className="text-sm font-semibold">Lost To<select value={form.lostToCompetitorId} onChange={(e)=>set("lostToCompetitorId",e.target.value)} className="mt-1 w-full rounded border p-2"><option value="">Not recorded</option>{competitors.map((x)=><option key={x.id} value={x.id}>{x.displayName}</option>)}</select></label><label className="text-sm font-semibold">Competitor Rate incl. VAT<input min="0" step=".01" type="number" value={form.competitorQuotedRateInclVat} onChange={(e)=>set("competitorQuotedRateInclVat",e.target.value)} className="mt-1 w-full rounded border p-2" /></label><label className="text-sm font-semibold">Competitor Meal Basis<select value={form.competitorMealBasis} onChange={(e)=>set("competitorMealBasis",e.target.value)} className="mt-1 w-full rounded border p-2">{opts(["RO","BB","HB","FB","OTHER","UNKNOWN"])}</select></label><label className="text-sm font-semibold">Competitor Occupancy<select value={form.competitorOccupancyBasis} onChange={(e)=>set("competitorOccupancyBasis",e.target.value)} className="mt-1 w-full rounded border p-2">{opts(["SINGLE","DOUBLE","MIXED","UNKNOWN"])}</select></label><label className="text-sm font-semibold">Source Confidence<select value={form.competitorSourceConfidence} onChange={(e)=>set("competitorSourceConfidence",e.target.value)} className="mt-1 w-full rounded border p-2">{opts(["HIGH","MEDIUM","LOW"])}</select></label></>}
  {form.status==="DECLINED"&&<label className="text-sm font-semibold">Declined Reason<select value={form.declinedReason} onChange={(e)=>set("declinedReason",e.target.value)} className="mt-1 w-full rounded border p-2">{opts(DECLINED_REASONS)}</select></label>}<label className="text-sm font-semibold sm:col-span-2 lg:col-span-3">Notes<textarea value={form.notes} onChange={(e)=>set("notes",e.target.value)} className="mt-1 w-full rounded border p-2" /></label><label className="text-sm font-semibold sm:col-span-2 lg:col-span-3">Rate revision note<textarea value={form.rateNotes} onChange={(e)=>set("rateNotes",e.target.value)} className="mt-1 w-full rounded border p-2" /></label><div><button disabled={saving} className="rounded bg-[#b41f1f] px-4 py-2 font-semibold text-white disabled:bg-gray-400">{saving?"Saving…":"Update Outcome"}</button></div>{message&&<p role="status" className="text-sm font-semibold">{message}</p>}</form>;
}
